service: rtr-text-extraction
frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.9
  region: us-east-1

functions:
  - ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 3001

plugins:
  - serverless-offline
  - serverless-python-requirements
